/**
 * Python (pytest-playwright) variable emitter.
 *
 * Implements `VariableEmitter` for `.py` files generated by Playwright's
 * Python code generator (pytest-playwright style).
 *
 * Insertion point
 * ───────────────
 * Module-level constants are inserted ABOVE the first `def test_` function
 * definition (or class definition, whichever comes first).  If neither
 * exists the block is prepended to the file.
 *
 * Variable format
 * ───────────────
 *   VALID_EMAIL = "qa@example.com"
 *
 * Double-quoted strings are used because that is Python's conventional style
 * for string constants and matches Playwright's Python codegen output.
 * Values that contain double quotes are escaped as `\"`.
 * Values that contain newlines use triple-quoted strings.
 *
 * Collision policy
 * ────────────────
 * If an identifier with the same SCREAMING_SNAKE name already appears as an
 * assignment at module scope (`VAR_NAME = ...`) or as a local variable
 * (`VAR_NAME = ...` inside a function), the variable is skipped and a
 * warning is emitted to stderr.
 *
 * Inline substitution
 * ───────────────────
 * Every string literal occurrence of `oldValue` in the source is replaced
 * with the bare identifier `VAR_NAME`.
 *
 * Example:
 *   page.fill('input[name="email"]', 'qa@example.com')
 *   →
 *   page.fill('input[name="email"]', VALID_EMAIL)
 */

import type { DetectionResult, ExtractedVariable } from '../detector.js';
import type { VariableEmitter } from '../extract-orchestrator.js';

// ── Helpers ─────────────────────────────────────────────────────────────────

/**
 * Return the set of SCREAMING_SNAKE identifiers already assigned somewhere in
 * the Python source.  Matches bare `NAME = ...` assignments at any
 * indentation.
 */
function existingPyVarNames(content: string): Set<string> {
  const found = new Set<string>();
  const re = /^[ \t]*([A-Z][A-Z0-9_]*)\s*=/gm;
  let m: RegExpExecArray | null;
  while ((m = re.exec(content)) !== null) {
    found.add(m[1]);
  }
  return found;
}

/**
 * Determine which variables are safe to insert and warn about collisions.
 */
function resolveVars(
  variables: ExtractedVariable[],
  alreadyDefined: Set<string>,
): ExtractedVariable[] {
  return variables.filter((v) => {
    if (alreadyDefined.has(v.name)) {
      process.stderr.write(
        `[xlibrary wizard] WARNING: variable ${v.name} is already defined in the Python source — skipping extraction of value "${v.value}".\n`,
      );
      return false;
    }
    return true;
  });
}

/**
 * Escape a string value for use inside a Python double-quoted string literal.
 * Returns a triple-quoted string if the value contains a newline.
 */
function formatPyValue(value: string): string {
  if (value.includes('\n')) {
    // Triple-quoted — escape any triple-quote sequences inside.
    const escaped = value.replace(/"""/g, '\\"\\"\\"');
    return `"""${escaped}"""`;
  }
  const escaped = value.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
  return `"${escaped}"`;
}

/**
 * Build the block of module-level constant assignments.
 */
function buildConstBlock(vars: ExtractedVariable[]): string {
  return vars.map((v) => `${v.name} = ${formatPyValue(v.value)}`).join('\n');
}

/**
 * Find the insertion index for the constant block.
 *
 * Inserts ABOVE the first `def test_` function or `class Test` / `class test`
 * definition (case-insensitive on the class name prefix).
 * If neither is found, inserts at the very beginning of the file (after any
 * leading `# coding: ...` or shebang line, i.e. after the first two lines
 * at most — but only if they start with `#` or `#!/`).
 */
function findInsertionIndex(content: string): number {
  // Look for first `def test_` or class definition.
  const defRe = /^(?:def test_|class [A-Za-z])/m;
  const defMatch = defRe.exec(content);
  if (defMatch !== null) return defMatch.index;

  // No test function — check for a shebang / coding comment at top.
  const lines = content.split('\n');
  let skipLines = 0;
  for (const line of lines.slice(0, 2)) {
    if (line.startsWith('#')) skipLines++;
    else break;
  }
  if (skipLines > 0) {
    // Insert after those header lines.
    return lines.slice(0, skipLines).join('\n').length + 1; // +1 for '\n'
  }

  return 0;
}

/**
 * Replace string literal occurrences of `literal` with the bare identifier
 * `varName` in the Python source.
 *
 * Handles single-quoted (`'value'`) and double-quoted (`"value"`) forms.
 * Does NOT handle triple-quoted strings (rare in generated code).
 */
function replacePyLiteral(content: string, literal: string, varName: string): string {
  const escaped = literal.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const reSingle = new RegExp(`'${escaped}'`, 'g');
  const reDouble = new RegExp(`"${escaped}"`, 'g');
  return content.replace(reSingle, varName).replace(reDouble, varName);
}

/**
 * Apply all substitutions for variables that were not skipped.
 */
function applySubstitutions(
  content: string,
  substitutions: Map<number, { varName: string; oldValue: string }[]>,
  skippedVars: Set<string>,
): string {
  const replacements = new Map<string, string>();
  for (const subs of substitutions.values()) {
    for (const sub of subs) {
      if (skippedVars.has(sub.varName)) continue;
      if (!replacements.has(sub.oldValue)) {
        replacements.set(sub.oldValue, sub.varName);
      }
    }
  }
  let result = content;
  for (const [literal, varName] of replacements) {
    result = replacePyLiteral(result, literal, varName);
  }
  return result;
}

// ── Public emitter ───────────────────────────────────────────────────────────

/**
 * Python pytest-playwright `VariableEmitter` implementation.
 */
export const pythonEmitter: VariableEmitter = {
  applyExtraction(sourceContent: string, result: DetectionResult): string {
    const alreadyDefined = existingPyVarNames(sourceContent);
    const safeVars = resolveVars(result.variables, alreadyDefined);
    const skippedVars = new Set(
      result.variables.filter((v) => alreadyDefined.has(v.name)).map((v) => v.name),
    );

    // 1. Apply substitutions FIRST on the original source so that the literal
    //    values inside the constant declarations we are about to insert are
    //    never matched by the replacer.
    const substituted = applySubstitutions(sourceContent, result.substitutions, skippedVars);

    if (safeVars.length === 0) return substituted;

    // 2. Insert the constant block into the already-substituted content.
    const constBlock = buildConstBlock(safeVars);
    const insertIdx = findInsertionIndex(substituted);
    return substituted.slice(0, insertIdx) + constBlock + '\n\n' + substituted.slice(insertIdx);
  },
};

// Named exports for unit tests.
export {
  existingPyVarNames,
  resolveVars as resolvePyVars,
  buildConstBlock as buildPyConstBlock,
  findInsertionIndex as findPyInsertionIndex,
};
