/**
 * TypeScript (Playwright Test) variable emitter.
 *
 * Implements `VariableEmitter` for `.ts` files generated by Playwright's TS
 * code generator.  The emitter inserts `const VAR_NAME = 'value';` declarations
 * at the top of the file, immediately after the last import statement and
 * before the first `test(` call.
 *
 * Insertion point
 * ───────────────
 * The emitter scans for:
 *   1. The last `import` line (any `import ... from ...` pattern).
 *   2. If no imports exist, falls back to inserting before the first `test(`
 *      or `describe(` call.
 *   3. If neither pattern is found, prepends to the file.
 *
 * Variable format
 * ───────────────
 *   const VALID_EMAIL = 'qa@example.com';
 *
 * Single-quoted string literals are used because Playwright's TS codegen
 * uses single-quotes as its default string delimiter.
 * Values that contain single quotes are escaped as `\'`.
 * Values that contain newlines are rendered as template literals.
 *
 * Collision policy
 * ────────────────
 * If `const VAR_NAME` (or `let VAR_NAME` / `var VAR_NAME`) already appears in
 * the source, the variable is skipped and a warning is emitted to stderr.
 *
 * Inline substitution
 * ───────────────────
 * After inserting the declarations the emitter replaces each string literal
 * occurrence of `oldValue` with the bare identifier `VAR_NAME`.
 *
 * Example:
 *   await page.fill('input[name="email"]', 'qa@example.com');
 *   →
 *   await page.fill('input[name="email"]', VALID_EMAIL);
 *
 * Note: both `'value'` and `"value"` occurrences are replaced because
 * Playwright codegen sometimes emits double-quoted strings.
 */

import type { DetectionResult, ExtractedVariable } from '../detector.js';
import type { VariableEmitter } from '../extract-orchestrator.js';

// ── Helpers ─────────────────────────────────────────────────────────────────

/**
 * Return the set of identifier names already declared as variables in the
 * TypeScript source.  Matches `const`, `let`, and `var` declarations at any
 * indentation level.
 */
function existingTsVarNames(content: string): Set<string> {
  const found = new Set<string>();
  const re = /(?:const|let|var)\s+([A-Z][A-Z0-9_]*)\s*=/gm;
  let m: RegExpExecArray | null;
  while ((m = re.exec(content)) !== null) {
    found.add(m[1]);
  }
  return found;
}

/**
 * Determine which variables are safe to insert and warn about collisions.
 */
function resolveVars(
  variables: ExtractedVariable[],
  alreadyDefined: Set<string>,
): ExtractedVariable[] {
  return variables.filter((v) => {
    if (alreadyDefined.has(v.name)) {
      process.stderr.write(
        `[xlibrary wizard] WARNING: variable ${v.name} is already defined in the TypeScript source — skipping extraction of value "${v.value}".\n`,
      );
      return false;
    }
    return true;
  });
}

/**
 * Escape a string value for use inside a single-quoted TS string literal.
 * Returns a template literal if the value contains a newline.
 */
function formatTsValue(value: string): string {
  if (value.includes('\n')) {
    // Template literal — escape backticks and `$` that precede `{`.
    const escaped = value.replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
    return `\`${escaped}\``;
  }
  const escaped = value.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
  return `'${escaped}'`;
}

/**
 * Build the block of `const` declarations to insert.
 */
function buildConstBlock(vars: ExtractedVariable[]): string {
  return vars.map((v) => `const ${v.name} = ${formatTsValue(v.value)};`).join('\n');
}

/**
 * Find the insertion index for the const declarations.
 *
 * Returns the character index in `content` immediately after the last import
 * statement (including its trailing newline).  If no imports are found,
 * returns the index of the first `test(` or `describe(` call.  If neither is
 * found, returns 0 (prepend).
 */
function findInsertionIndex(content: string): number {
  // Find the last `import` line.
  const importRe = /^import\s+.+\s*;?\s*$/gm;
  let lastImportEnd = -1;
  let m: RegExpExecArray | null;
  while ((m = importRe.exec(content)) !== null) {
    const end = m.index + m[0].length;
    if (end > lastImportEnd) lastImportEnd = end;
  }

  if (lastImportEnd !== -1) {
    // Move past the trailing newline (if present).
    const nextChar = content[lastImportEnd];
    if (nextChar === '\n') return lastImportEnd + 1;
    if (nextChar === '\r' && content[lastImportEnd + 1] === '\n') return lastImportEnd + 2;
    return lastImportEnd;
  }

  // No imports — insert before the first test( / describe( call.
  const testRe = /^(?:test|describe)\s*\(/m;
  const testMatch = testRe.exec(content);
  if (testMatch !== null) return testMatch.index;

  return 0;
}

/**
 * Replace string literal occurrences of `literal` with the bare identifier
 * `varName` in the TypeScript source.
 *
 * Handles both single-quoted (`'value'`) and double-quoted (`"value"`) forms.
 * Does NOT handle template literals because Playwright codegen does not emit
 * them for recorded values.
 */
function replaceTsLiteral(content: string, literal: string, varName: string): string {
  // Escape characters that are special in a regex character class or body.
  const escapedLiteral = literal.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  // Replace 'literal' and "literal"
  const reSingle = new RegExp(`'${escapedLiteral}'`, 'g');
  const reDouble = new RegExp(`"${escapedLiteral}"`, 'g');
  return content.replace(reSingle, varName).replace(reDouble, varName);
}

/**
 * Apply all substitutions for variables that were not skipped.
 */
function applySubstitutions(
  content: string,
  substitutions: Map<number, { varName: string; oldValue: string }[]>,
  skippedVars: Set<string>,
): string {
  const replacements = new Map<string, string>();
  for (const subs of substitutions.values()) {
    for (const sub of subs) {
      if (skippedVars.has(sub.varName)) continue;
      if (!replacements.has(sub.oldValue)) {
        replacements.set(sub.oldValue, sub.varName);
      }
    }
  }
  let result = content;
  for (const [literal, varName] of replacements) {
    result = replaceTsLiteral(result, literal, varName);
  }
  return result;
}

// ── Public emitter ───────────────────────────────────────────────────────────

/**
 * TypeScript Playwright Test `VariableEmitter` implementation.
 */
export const typescriptEmitter: VariableEmitter = {
  applyExtraction(sourceContent: string, result: DetectionResult): string {
    const alreadyDefined = existingTsVarNames(sourceContent);
    const safeVars = resolveVars(result.variables, alreadyDefined);
    const skippedVars = new Set(
      result.variables.filter((v) => alreadyDefined.has(v.name)).map((v) => v.name),
    );

    // 1. Apply substitutions FIRST on the original source.
    //    The const declarations have not been inserted yet, so the literal
    //    values inside `const VALID_EMAIL = 'qa@example.com';` are never
    //    visited by the replacer — only the actual usage sites in the test
    //    body are substituted.
    const substituted = applySubstitutions(sourceContent, result.substitutions, skippedVars);

    if (safeVars.length === 0) return substituted;

    // 2. Insert the const block into the already-substituted content.
    //    `findInsertionIndex` still works correctly because the import lines
    //    were not modified by the substitution step.
    const constBlock = buildConstBlock(safeVars);
    const insertIdx = findInsertionIndex(substituted);
    return substituted.slice(0, insertIdx) + constBlock + '\n\n' + substituted.slice(insertIdx);
  },
};

// Named exports for unit tests.
export { existingTsVarNames, resolveVars as resolveTsVars, buildConstBlock, findInsertionIndex };
